### ISSUE TITLE
Inputted settings for EffectTimedDur don't work

### ISSUE THREAD

**Issue by doomdrvk** [pongo1231/ChaosModV#1]
I've tested and my friend has tested it, we had it set for 60 seconds but its staying at 180

**Comment by pongo1231** [comment]
This should be fixed now with 46230d0. Could you test it with this dll?


[ChaosMod.zip](https://github.com/pongo1231/ChaosModV/files/3693685/ChaosMod.zip)

**Comment by pongo1231** [comment]
Seems to be properly working now for other people since 1.0, so I'll mark this as resolved.
